#!/bin/bash


commit="$( \
  FZF_DEFAULT_COMMAND='git log --decorate --pretty="format:%Cgreen%h%Creset %Cblue%d%Creset %s" --color=always' \
  fzf --tiebreak=begin,index +s --ansi \
    --preview='echo {} | cut -d" " -f1 | xargs -n1 git show --color=always' \
)"

if [[ -n $commit ]]; then
  commit="$(echo -n "$commit" | cut -d' ' -f1)"
  git log -n1 --pretty=oneline "$commit"
  canContinue='y'
  read -n 1 -p "Fix this commit (Y/n)? " canContinue
  if [[ $canContinue =~ [yY] ]]; then
    git commit --fixup="$commit" "$@"
  fi
else
  exit 1
fi
