#!/bin/bash

function semver_tags() {
	git tag -l | grep -E '^v?[0-9.]+$' | sort -V
}

function latest_tag() {
	semver_tags | tail -1
}

function main() {
	local tag=$(latest_tag)
	if [[ "x$tag" == "x" ]]; then
		( >&2 echo "No semver tags found")
		exit 1
	fi
}

main $@

