#!/bin/bash

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
	echo "Usage: $0"
	echo "Finds leftover junk from merges and prompts for deletion"
	exit 1
fi

files=$(find . -regex '\(.*\.\(BASE\|LOCAL\|REMOTE\|BACKUP\)\..*\)\|\(.*\.orig$\)\|\(.*~HEAD$\)' | sort)
for f in $files; do
	echo $f
done
if [[ "x$files" != "x" ]]; then
	echo -ne "\n\nDelete these? [y|N]: "
	read x
	if [[ $x == 'y' ]]; then
		find . -regex '\(.*\.\(BASE\|LOCAL\|REMOTE\|BACKUP\)\..*\)\|\(.*\.orig$\)\|\(.*~HEAD$\)' -delete
	fi
else
	echo "No junk found."
fi
