#!/bin/bash

for b in $(git b); do echo -e "${b}\t$(git log --pretty="format:%ct\t%cr" -n1 "$b")"; done | sort -t$'\t' -k2 -n  | perl -F"/\t/" -e 'chomp for @F; printf("%-14s%s\n", $F[2] . ":", $F[0])'
