#!/bin/sh

FN=$1
if [ "x$FN" = "x" ]; then
	echo "Usage: $0 <file> [<REV>]"
	exit 1
fi

REV=${2:-HEAD^}

OUTFN="${REV}_${FN}"
OUTFN=$(echo "$OUTFN" | sed -r 's/\W+/_/g')
git cat-file blob "${REV}:${FN}" > "/tmp/$OUTFN"
echo "$FN $REV $OUTFN"
TOOL="$(git config diff.tool)"
if [ "x$GIT_EXTERNAL_DIFF" != "x" ]; then
	TOOL="$GIT_EXTERNAL_DIFF"
fi
if [ "x$TOOL" = "x" ]; then
	TOOL="meld"
fi
$TOOL "/tmp/$OUTFN" $FN
