#!/bin/bash

REMOTE=""
BRANCH="dev"
LIST=""

function usage() {
	echo "Usage: $0 [-s] <remote> <branch>"
	echo "Quick-and-dirty deployment:"
	echo
	echo "SSH to remote, and then within remote repo"
	echo " fetch and rebase branch"
	echo
	echo "-s = simulate, dry-run"
	exit 1
}

parseOpts() {
	while getopts "shr:" opt; do
		case $opt in
			h) usage  ;;
			s) LIST=1 ;;
			r) REMOTE="$OPTARG" ;;
			*) usage ;;
		esac
	done
	shift $(( $OPTIND - 1 ))

	REMOTE="${REMOTE:-$1}"
	REMOTE="${REMOTE:-origin}"
	URL=$(git config "remote.$REMOTE.url")
	HOST=$(echo -n $URL | sed -r 's@.+://([^/:]+).+@\1@')
	RPATH=$(echo -n $URL | sed -r 's@.+://[^/:]+(.+)$@\1@;s/\.git$//')
}

main() {
	[ -z "$LIST" ] && echo "SSH to $HOST"
	[ -z "$LIST" ] && echo "And CD to $RPATH"

	if [ -n "$LIST" ]; then
		echo "ssh $HOST:$RPATH"
	else
		ssh -t "$HOST" "cd \"$RPATH\"; git rebase $BRANCH || bash";
		echo "Deployed by rebase to $BRANCH"
	fi
}

parseOpts "$@"
main 
