#!/bin/bash

tool="find"
args=". -regex "
regex='\(_\(BASE\|LOCAL\|REMOTE\|BACKUP\)_\)\|\(\.orig$\)\|\(~HEAD$\)'
print0Arg="-print0"


if which ag > /dev/null; then
	tool="$(which ag)"
	regex=$(echo $regex | sed -r 's/\\([()|])/\1/g')
	print0Arg="--print0"
	args=". -g "
fi

if which fdfind > /dev/null; then
	tool="$(which fdfind)"
	regex=$(echo $regex | sed -r 's/\\([()|])/\1/g')
	print0Arg="-0"
	args=""
fi

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
	echo "Usage: $0"
	echo "Finds leftover junk from merges and prompts for deletion"
	exit 1
fi

#echo $tool $args "'$regex'"

files=$("$tool" $args "$regex" | sort)
for f in $files; do
	echo $f
done
if [[ "x$files" != "x" ]]; then
	echo -ne "\n\nDelete these? [y|N]: "
	read x
	if [[ $x == 'y' ]]; then
		"$tool" $args "$regex" $print0Arg | xargs -0 rm
	fi
else
	echo "No junk found."
fi
