#!/bin/bash

ONLYCHANGED=0
ONLYDROPBOX=0

function usage() {
	echo "Usage: $0 [-O] [-d]"
	echo "-O	Only show changed (ignore untracked)"
	echo "-d	Only show thoe which have a 'dropbox' remote"
	exit 1
}

while getopts "Od" opt; do
	case $opt in
		h) usage  ;;
		O) ONLYCHANGED=1 ;;
		d) ONLYDROPBOX=1 ;;
		*) usage ;;
	esac
done
shift $(( $OPTIND - 1 ))



for DIR in $(find . -name .git | sort); do
	pushd $(dirname "$DIR") > /dev/null
	STATUS=$(git status --porcelain \
		| perl -MData::Dumper -ne '
			BEGIN { $c = {M=>0,T=>0,D=>0,"??"=>0}; }
			$_ =~ s/^\s+|\s+$//;
			($s, $fn) = split(/\s+/,$_);
			$c->{$s}++; 
			END {
				$s = 0;  $s += $c->{$_} for keys %$c;
				if ($s == 0) {
					exit 0;
				} else {
					print join("|", grep {$c->{$_} != 0} (keys %$c));
					exit ($c->{M} ? 2 : 1);
				}
			}
			')
	EX=$?
	if [[ $EX == 1 && $ONLYCHANGED -ne 0 ]]; then
		echo -e "$DIR: $STATUS"
	elif [ $EX == 2 ]; then
		if [[ $ONLYDROPBOX -eq 1 ]]; then
			git remote | grep -q dropbox
			if [ $? == 0 ]; then
				echo -e "\e[31;1m$DIR: $STATUS\e[0m"
			fi
		else
			echo -e "\e[31;1m$DIR: $STATUS\e[0m"
		fi
	#else
		#echo "exit $EX"
	fi
	popd > /dev/null
done
