#!/usr/bin/perl

use warnings;
use strict;

print "TODO: git log | grep ^LOCAL\n";
print "Then find hash before first LOCAL, and reset --hard to there\n";
print "...making VERY sure to prompt, and check for uncommitted changes first\n";
print "Perhaps we should create a tag/branch beforehand\n\n\n";

print "Did nothing.\n";
