#!/bin/bash
# This allows you to keep a git repository store in your Dropbox folder.

# Usage from within working directory:
# git dropbox-init [dropbox-repo-name]
#
# If provided, dropbox-repo-name will be used instead of the default
# which would be e.g. for a working dir named 'source', source.git

BASE_DIR=~/Dropbox/code # Change this to move your repository store

if [ "$1" = '-h' -o "$1" = '--help' ]; then
	echo "Usage: $0 [target_repo_name]"
	exit 1
fi

target="$1"
repo=$(basename $PWD)
src="$PWD"
pushd "$BASE_DIR" > /dev/null 

if [ "x$target" != "x" ]; then
	if [ "${target%%.git}" == "$target" ]; then
		target="${target}.git"
	fi	
	repo="$target"
else
	target="$repo"
	if [ "${target%%.git}" == "$target" ]; then
		target="${target}.git"
	fi	
fi

git clone --bare "$src" "$target"
if [ $? -ne 0 ]; then
	echo "Failed to create remote repo -- may already exist by this name?"
	popd > /dev/null
	exit 1
fi

popd > /dev/null

git remote add dropbox "${BASE_DIR}/${repo}"
git fetch dropbox
git branch --set-upstream-to master remotes/dropbox/master
git push dropbox
